name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7.0.1

      - name: Login to docker hub
        uses: docker/login-action@v4.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend
        uses: docker/build-push-action@v7.3.0
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-assignment:latest
        
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          mkdir -p ~/devops-assignment
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Copy the compose file on the server
        run: |
          scp -i ~/.ssh/id_rsa docker-compose.yml \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/devops-assignment/docker-compose.yml

      - name: Deploy over SSH
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "DOCKER_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} bash -s" << 'EOF'
            cd ~/devops-assignment
            export DOCKER_USERNAME
            docker compose -f docker-compose.yml pull
            docker compose up -d --wait
          EOF
